### PR TITLE
Issue 395: Fix Test Suite job intermittently timeout Problem and Clippy related issues.

### LINKED ISSUE #395: Github CI Test Suite job intermittently timeout
**Problem description**
Github CI Test Suite job intermittently got stuck and timeout happens after 30 mins as we set. When the issue happens, it would pop up with the following call stack every 10 seconds.
```
Aug 05, 2022 10:54:45 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated@4a006835
java.lang.NullPointerException: startCall() returned a null listener for method io.pravega.controller.stream.api.grpc.v1.ControllerService/getCurrentSegments
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:636)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:612)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1800(ServerImpl.java:402)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:543)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:518)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Problem location**
https://github.com/pravega/pravega-client-rust/runs/7689747158?check_suite_focus=true

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by a6dulaleem**
**Change log description**  
Fixes the Test suit job intermittently timeout problem. also fixes Clippy related issues like duplicate default method etc.

Purpose of the change
Fixes #395 #404 

**What the code does**  
The code does following :-
1- Creates a internal function reader_offline.
2- Calls that method inside one of thread in the destructor.
3- Initializes the values of readerState to default
4- Drops the unused lock (which was causing the deadlock) 
5- Fixes the clippy related issue by following the clippy rules

**How to verify it**  
This can be verified on local by running following 

```
 cargo fmt --check --all
 cargo clippy --workspace
 cargo test -p pravega-connection-pool -p pravega-client-channel -p pravega-controller-client -p pravega-client-integration-test -p pravega-client-retry -p pravega-client-shared -p pravega-wire-protocol -p pravega-client -p pravega-client-auth -p pravega-client-config
```

### CODE REVIEW

**Comment by thekingofcity** [comment]
Great to see clippy is finally fixed :)

File: nodejs/src/lib.rs [hunk 1]
```diff
@@ -10,7 +10,7 @@
 // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 // See the License for the specific language governing permissions and
 // limitations under the License.
-
+#![allow(clippy::result_large_err)] // https://github.com/rust-lang/rust-clippy/issues/8971
```
Comment (tkaitchuck) [inline nodejs/src/lib.rs:13]: This issue appears unrelated to this allow.

File: src/event/reader.rs [hunk 2]
```diff
@@ -382,41 +394,41 @@ impl EventReader {
...
-            info!("Putting reader {:?} offline", self.id);
+    async fn reader_offline_internal(
+        reader_id: Reader,
+        rg_state: Arc<Mutex<ReaderGroupState>>,
+        meta: &mut ReaderState,
+    ) -> Result<(), EventReaderError> {
+        let mut rg_guard = rg_state.lock().await;
+        let online = rg_guard.check_online(&reader_id).await;
+        drop(rg_guard);
+        if !meta.reader_offline && online {
```
Comment (tkaitchuck) [inline src/event/reader.rs:405]: I believe this can all be inlined into one line. The if the guard is never assigned to a variable it will be dropped at the end of the line.

**Review by tkaitchuck — APPROVED** [review]

**Review by anishakj — APPROVED** [review]
LGTM

**Review by ShwethaSNayak — APPROVED** [review]
LGTM

**Review by tkaitchuck — APPROVED** [review]
