### PR TITLE
Issue 245: Retry when controller receives unauthenticated error

### LINKED ISSUE #245: Keycloak authentication token does not get refreshed
**Problem description**
An application that uses the byte stream reader to read from Pravega with Keycloak authentication works well for 5 minutes and then it panics. This is likely caused by not refreshing the token.

```
thread 'tokio-runtime-worker' panicked at 'get endpoint for async segment reader: RetryError { error: OperationError { can_retry: false, operation: "get_endpoint", error_msg: "status: Unauthenticated, message: \"\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"authorization\": \"Bearer snipped\"} }" }, total_delay: 0ns, tries: 1 }', /mnt/home/faheyc/nautilus/gstreamer/gstreamer-pravega/pravega-client-rust/src/segment_reader.rs:229:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: std::panicking::try
   7: tokio::runtime::task::harness::poll_future
   8: tokio::runtime::task::harness::Harness<T,S>::poll
   9: std::thread::local::LocalKey<T>::with
  10: tokio::runtime::thread_pool::worker::Context::run_task
  11: tokio::runtime::thread_pool::worker::Context::run
  12: tokio::macros::scoped_tls::ScopedKey<T>::set
  13: tokio::runtime::thread_pool::worker::run
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::blocking::pool::Inner::run

```

**Problem location**
Keycloak client.

**Suggestions for an improvement**
None.

### PR DESCRIPTION
**Pull request by Tristan1900**
**Change log description**  
Controller received error `Unauthenticated` when calling `get_segment` method. It could be caused by token expiry so we need to refresh the controller token and retry instead of `panic`.

**Purpose of the change**  
Fix #245 

**What the code does**  
Reset the controller connection and refresh the auth token when `Unauthenticated` happened.

**How to verify it**  
All the existing tests should pass.

### CODE REVIEW

File: src/transaction/pinger.rs [hunk 1]
```diff
@@ -149,7 +143,15 @@ impl Pinger {
             info!("sending transaction pings complete.");
 
             // delay for transaction lease milliseconds.
-            sleep(Duration::from_millis(self.txn_lease_millis)).await;
+            tokio::select! {
+                _ = sleep(Duration::from_millis(self.txn_lease_millis)) => {
+                    debug!("pinger wake up after {}ms", self.txn_lease_millis);
+                }
+                _ = &mut self.shutdown => {
+                    info!("shut down pinger");
```
Comment (shrids) [inline src/transaction/pinger.rs:151]: nit: we could log the txn Id here

**Review by shrids — APPROVED** [review]
