### PR TITLE
Issue 267: Remove runtime drop error message

### LINKED ISSUE #267: Panic on shutdown prevents flush
When running the gstreamer plugin a user encountered this:
```
+++ dirname ./scripts/pravega-to-file.sh
++ readlink -f ./scripts/..
+ ROOT_DIR=/home/sumit/Pravega-Idea/gstreamer-pravega
+ pushd /home/sumit/Pravega-Idea/gstreamer-pravega/gst-plugin-pravega
~/Pravega-Idea/gstreamer-pravega/gst-plugin-pravega ~/Pravega-Idea/gstreamer-pravega
+ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
+ ls -lh /home/sumit/Pravega-Idea/gstreamer-pravega/target/debug/libgstpravega.so
-rwxrwxr-x 2 sumit sumit 325M May 16 07:56 /home/sumit/Pravega-Idea/gstreamer-pravega/target/debug/libgstpravega.so
+ export GST_PLUGIN_PATH=/home/sumit/Pravega-Idea/gstreamer-pravega/target/debug:
+ GST_PLUGIN_PATH=/home/sumit/Pravega-Idea/gstreamer-pravega/target/debug:
+ export GST_DEBUG=pravegasrc:LOG
+ GST_DEBUG=pravegasrc:LOG
+ export PRAVEGA_VIDEO_LOG=info
+ PRAVEGA_VIDEO_LOG=info
+ export RUST_BACKTRACE=1
+ RUST_BACKTRACE=1
+ PRAVEGA_CONTROLLER_URI=127.0.0.1:9090
+ PRAVEGA_SCOPE=examples
+ PRAVEGA_STREAM=split2
+ ALLOW_CREATE_SCOPE=true
+ OUTPUT_FILE=/home/sumit/split2.ts
+ gst-launch-1.0 -v pravegasrc stream=examples/split2 controller=127.0.0.1:9090 allow-create-scope=true '!' filesink location=/home/sumit/split2.ts sync=false
0:00:00.064894554  7847 0x557c06b36640 DEBUG             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:780:gstpravega::pravegasrc::imp:<pravegasrc0> query: BEGIN: query=Query { ptr: 0x557c06980c00, type: "caps", structure: Some(GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)"NULL";) }
0:00:00.064972032  7847 0x557c06b36640 DEBUG             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:831:gstpravega::pravegasrc::imp:<pravegasrc0> query: END: result=true, query=Query { ptr: 0x557c06980c00, type: "caps", structure: Some(GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)ANY;) }
0:00:00.065034898  7847 0x557c06b36640 DEBUG             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:780:gstpravega::pravegasrc::imp:<pravegasrc0> query: BEGIN: query=Query { ptr: 0x557c06980ca0, type: "caps", structure: Some(GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)"NULL";) }
0:00:00.065078946  7847 0x557c06b36640 DEBUG             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:831:gstpravega::pravegasrc::imp:<pravegasrc0> query: END: result=true, query=Query { ptr: 0x557c06980ca0, type: "caps", structure: Some(GstQueryCaps, filter=(GstCaps)"NULL", caps=(GstCaps)ANY;) }
Setting pipeline to PAUSED ...
0:00:00.065343154  7847 0x557c06b36640 DEBUG             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:517:gstpravega::pravegasrc::imp:<pravegasrc0> start: BEGIN
0:00:00.065384665  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:535:gstpravega::pravegasrc::imp:<pravegasrc0> start: scope=examples, stream=split2, index_stream=split2-index
0:00:00.065426388  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:536:gstpravega::pravegasrc::imp:<pravegasrc0> start: start_mode=Earliest, end_mode=Unbounded
0:00:00.065455121  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:541:gstpravega::pravegasrc::imp:<pravegasrc0> start: controller=127.0.0.1:9090
0:00:00.065488100  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:543:gstpravega::pravegasrc::imp:<pravegasrc0> start: keycloak_file=None
0:00:00.065691583  7847 0x557c06b36640 DEBUG             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:547:gstpravega::pravegasrc::imp:<pravegasrc0> start: config=ClientConfig { max_connections_in_pool: 4294967295, max_controller_connections: 3, connection_type: Tokio, retry_policy: RetryWithBackoff { current: 1, base: 10, max_delay: Some(10s) }, controller_uri: PravegaNodeUri("127.0.0.1:9090"), transaction_timeout_time: 90000, mock: false, trustcert: "./ca-cert.crt", is_tls_enabled: false, credentials: Credentials { inner: Basic { method: "Basic", token: "Og==" } }, is_auth_enabled: false, reader_wrapper_buffer_size: 1048576, request_timeout: 30s }
0:00:00.065748272  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:548:gstpravega::pravegasrc::imp:<pravegasrc0> start: controller_uri=127.0.0.1:9090
0:00:00.065767384  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:549:gstpravega::pravegasrc::imp:<pravegasrc0> start: is_tls_enabled=false
0:00:00.065784903  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:550:gstpravega::pravegasrc::imp:<pravegasrc0> start: is_auth_enabled=false
0:00:00.067289934  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:557:gstpravega::pravegasrc::imp:<pravegasrc0> start: allow_create_scope=true
0:00:00.379170643  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:604:gstpravega::pravegasrc::imp:<pravegasrc0> start: Opened Pravega reader for data
0:00:00.389535994  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:612:gstpravega::pravegasrc::imp:<pravegasrc0> start: Opened Pravega reader for index
0:00:00.389593971  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:641:gstpravega::pravegasrc::imp:<pravegasrc0> start: end_offset=18446744073709551615
0:00:00.389790703  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:651:gstpravega::pravegasrc::imp:<pravegasrc0> start: Started
0:00:00.389842292  7847 0x557c06b36640 DEBUG             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:654:gstpravega::pravegasrc::imp:<pravegasrc0> start: END: result=Ok(())
0:00:00.390030387  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:680:gstpravega::pravegasrc::imp:<pravegasrc0> do_seek: BEGIN: segment=Segment { format: Time, start: "0:00:00.000000000", offset: "0:00:00.000000000", stop: "--:--:--.---------", rate: 1.0, applied_rate: 1.0, flags: (empty), time: "0:00:00.000000000", base: "0:00:00.000000000", position: "0:00:00.000000000", duration: "--:--:--.---------" }
0:00:00.390079707  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:730:gstpravega::pravegasrc::imp:<pravegasrc0> do_seek: initial_seek=true
0:00:00.390204092  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:739:gstpravega::pravegasrc::imp:<pravegasrc0> do_seek: seeking to timestamp=1970-01-01T00:00:00.000000000Z (0 ns, 0:00:00.000000000)
0:00:00.392529942  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:742:gstpravega::pravegasrc::imp:<pravegasrc0> do_seek: index_record=Err(Custom { kind: UnexpectedEof, error: "Index has no records" })
0:00:00.392783928  7847 0x557c06b36640 ERROR             pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:755:gstpravega::pravegasrc::imp:<pravegasrc0> do_seek: index is empty; segment=Segment { format: Time, start: "0:00:00.000000000", offset: "0:00:00.000000000", stop: "--:--:--.---------", rate: 1.0, applied_rate: 1.0, flags: (empty), time: "0:00:00.000000000", base: "0:00:00.000000000", position: "0:00:00.000000000", duration: "--:--:--.---------" }
0:00:00.392833127  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:775:gstpravega::pravegasrc::imp:<pravegasrc0> do_seek: END: result=false
0:00:00.393087436  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:836:gstpravega::pravegasrc::imp:<pravegasrc0> stop: BEGIN
0:00:00.393204443  7847 0x557c06b36640 INFO              pravegasrc gst-plugin-pravega/src/pravegasrc/imp.rs:848:gstpravega::pravegasrc::imp:<pravegasrc0> stop: END: result=Ok(())
ERROR: Pipeline doesn't want to pause.
thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/sumit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/shutdown.rs:51Setting pipeline to NULL ...
:21
stack backtrace:
Freeing pipeline ...
```

Tokio panicked because the Runtime was blocked in an async context. This prevented the flush and resulted in no output.
Also submitted as: https://github.com/pravega/gstreamer-pravega/issues/61

### PR DESCRIPTION
**Pull request by Tristan1900**
**Change log description**  
Remove runtime drop error message.
Upgrade tonic version to 0.5, prost version to 0.8 as prost version 0.7 is having problem with `rustc 1.56.0-nightly (50171c310 2021-09-01)` [ref](https://github.com/tokio-rs/prost/issues/526).

**Purpose of the change**  
Fix #267 #308 #253

**What the code does**  
ClientFactory is the only place that contains the Runtime and it cannot be cloned, so there is only one place that's holding the runtime now.
Make another struct ClientFacotryAsync that holds `Runtime::Handle`, which can be cloned and used in async context.

**How to verify it**  
Test should pass

### CODE REVIEW

File: config/src/lib.rs [hunk 1]
```diff
@@ -223,9 +223,11 @@ impl ClientConfigBuilder {
 mod tests {
     use super::*;
     use base64::encode;
+    use serial_test::serial;
     use std::net::Ipv4Addr;
 
     #[test]
+    #[serial]
```
Comment (tkaitchuck) [inline config/src/lib.rs:230]: I don't understand why these tests can't be run in parallel. This is testing config values.
If it's modifying environment variables, can we split that out into its own test so it don't affect others too much?

**Comment by shrids** [comment]
Thanks @Tristan1900 . Regarding the build failing for prost version 0.7 on rust rustc 1.56.0-nightly , I have moved the build to use the stable version of rustc in PR: #312

**Comment by Tristan1900** [comment]
@shrids Thanks Sandeep. I guess we can keep the Tonic upgrade in this PR since we will need to upgrade at some point in the future anyway.

File: config/src/lib.rs (hunk 1 above)
Comment (Tristan1900) [reply config/src/lib.rs:230]: Yes it's because the env var is a shared resource and running unit tests in parallel will have issues. 
I have been googling around and cannot find a better way to deal with shared resource like env var in the unit test. Either we run it consecutively or run it using only 1 thread.

File: controller-client/src/lib.rs [hunk 2]
```diff
@@ -325,9 +327,24 @@ pub trait ControllerClient: Send + Sync {
     async fn check_scale(&self, stream: &ScopedStream, scale_epoch: i32) -> ResultRetry<bool>;
 }
 
+#[derive(Clone)]
+struct AuthInterceptor {
+    token: Option<String>,
+}
+
+impl Interceptor for AuthInterceptor {
```
Comment (shrids) [inline controller-client/src/lib.rs:335]: Could you elaborate more on this change? I think it is unrelated to the PR.

File: python_binding/tox.ini [hunk 3]
```diff
@@ -13,6 +13,6 @@ deps =
     pytest
     pytest-timeout
     aiounittest
-commands = pytest {posargs:tests} --timeout=300 -vvvvv
+commands = pytest {posargs:tests} --timeout=300 -vvvvv -s
```
Comment (shrids) [inline python_binding/tox.ini:16]: -s disables capturing, capturing simplifies debugging if the tests fail.

File: controller-client/src/lib.rs (hunk 2 above)
Comment (Tristan1900) [reply controller-client/src/lib.rs:335]: Yes, it's the necessary change for upgrading Tonic version. I am following the example [here](https://github.com/hyperium/tonic/blob/master/examples/src/interceptor/client.rs#L45)

File: python_binding/tox.ini (hunk 3 above)
Comment (Tristan1900) [reply python_binding/tox.ini:16]: I see. I found that without -s we couldn't see the log printed out to the stdout, so it's not easy to debug when the tests are stuck at some place. 
I can revert it back

**Review by tkaitchuck — APPROVED** [review]

**Review by shrids — APPROVED** [review]
LGTM.
